# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b154f951b3fb0995704dae7d9baaf4be3efb9527dcac8265a9494507652b622914364b4a0a09395a935a404010095f2a2cd2126232c14c6b4731a80c04ff156d

test:
  secret_key_base: 8e1586195f922b6806f87351db3419ae2012110e33bfaa3289994c403bac83af554c89a0bb8abe74782608b7126a1b4ce51bcb33482ecbe257c11e8e7c98a4fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# development:
#   mailchimp_api_key: your-secret-api-key-goes-here 

# test:
#   mailchimp_api_key: your-secret-api-key-goes-here 

# production:
#   mailchimp_api_key: your-secret-api-key-goes-here 
 